config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root 'home#index'
  get 'home/about'
  get 'home/lookup'
  get 'home/show'
  post 'home/show' => 'home/show'
  post '/home/lookup' => 'home/lookup'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
    require "net/http"
    require "json"
    @url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)
    @crypto_symbols = []
    for x in @lookup_crypto
      @crypto_symbols << x["symbol"]
    end
    @profit_loss = 0
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
    require "net/http"
    require "json"
    @url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_crypto = JSON.parse(@response)
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
    require "net/http"
    require "json"
    @url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @new_crypto = JSON.parse(@response)
    @crypto_symbols = []
    user_cryptos = []
    for y in current_user.cryptos
      user_cryptos << y.symbol
    end
    for x in @new_crypto
    
        if !user_cryptos.include?( x["symbol"])
          @crypto_symbols << x["symbol"]
        end
    
    end
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
    
    def correct_user
      @correct = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "Not Authorized to edit this entry" if @correct.nil?
    end
    
    def get_coins
    
    
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @crypto_coins =  get_coins
  end
  
  def show
    
    @show_coins = get_coins
    
    
    @symbol = params[:sym]
    if @symbol
      @symbol = @symbol.downcase
    end
    @currency = "No such currency"
    for x in @show_coins
      if @symbol == x["symbol"]
        @currency = x
        
      end
    end
    
  end
  
  
  private 
  def get_coins
    require "net/http"
    require "json"
    @url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    JSON.parse(@response)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<div class="panel-heading">
  <h3 class="panel-title"><%= @header %></h3>
</div>
<div class="panel-body">
  <div class="form-group">
    <%= form_with(model: crypto, local: true) do |form| %>
      <% if crypto.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>
    
          <ul>
          <% crypto.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= form.label :crypto %><br/>
        <%= form.select :symbol , @crypto_symbols, class: "form-control" %>
      </div>
    
      <div class="field">
        
        <%= form.number_field :user_id, value: current_user.id, class: "form-control", type: "hidden" %>
      </div>
    
      <div class="field">
        <%= form.label :cost_per %>
        <%= form.number_field :cost_per, class: "form-control", step: "any"  %>
      </div>
    
      <div class="field">
        <%= form.label :amount_owned %>
        <%= form.number_field :amount_owned , class: "form-control", step: "any" %>
      </div>
    
      <div class="actions">
        <%= form.submit "Add", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>My Cryptos</h1>

<br/>
<table class = "table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Price</th>
      <th>24 hr %</th>
      <th>Total Value</th>
      <th>Total Paid</th>
      <th>Profit/Loss</th>
      <th>Cost Paid Per</th>
      <th>Amount owned</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <% if crypto.user_id == current_user.id %>
        <tr>
          <% for coin in @lookup_crypto %>
            <% if coin["symbol"].downcase == crypto.symbol.downcase %>
              <td><%= link_to  coin["name"] , crypto %></td>
              <td>$<%= coin["current_price"] %></td>
              <td><%= coin["price_change_percentage_24h"]%></td>
              <td>$<%= coin["current_price"].to_d * crypto.amount_owned %></td>
              <td>$<%= (crypto.cost_per * crypto.amount_owned) %></td>
              <td>$<%=  (coin["current_price"].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned) %></td>
              <td>$<%= crypto.cost_per %></td>
              <td><%= crypto.amount_owned %></td>
              <% @profit_loss += (coin["current_price"].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned) %>
            <% end %>
          <% end %>
          
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<p><strong>Total Loss Profit: </strong><%= number_to_currency(@profit_loss) %></p>

<%= link_to 'New Crypto', new_crypto_path, class: "btn btn-default" %>

app/views/cryptos/new.html.erb
<% @header = "New Crypto" %>
<div class="panel panel-default">
<%= render 'form', crypto: @crypto %>
    <div class="panel-footer"><%= link_to 'Back', cryptos_path %></div>
</div>

app/views/cryptos/show.html.erb
<% for coin in @show_crypto %>
  <% if coin["symbol"].downcase == @crypto.symbol.downcase %>
    <% crypto_name = coin["name"] %>
    <% crypto_price = coin["current_price"] %>
  <% end %>
<% end %>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= crypto_name %></h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Symbol:</strong>
      <%= @crypto.symbol %>
    </p>
    
    <p>
      <strong>Current Price:</strong>
      <%= crypto_price %>
    </p>
    
    <p>
      <strong>Cost per:</strong>
      <%= @crypto.cost_per %>
    </p>
    
    <p>
      <strong>Amount owned:</strong>
      <%= @crypto.amount_owned %>
    </p>
    
  </div>
  <div class="panel-footer"><%= link_to 'Edit', edit_crypto_path(@crypto) %> |
    <%= link_to 'Back', cryptos_path %> | 
    <%= link_to 'Delete Crypto Currency', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class= "alert alert-warning alert-dismissible">
        <button class = "close" data-dismiss = "alert">
            <i classc= "glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div,msg) %>
    </div>
<% end %>

app/views/home/_footer.html.erb
<nav class="navbar navbar-default navbar-static-bottom">
  <div class="container" style = "text-align: center">
    <p><strong>Author:</strong> Azmarino</p>
    <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>
    Azmarino, Inc 2019
  </div>
</nav>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crypto Portfolio", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li> <%= link_to "Add New", new_crypto_path %></li>
          <li> <%= link_to "My Cryptos", cryptos_path %></li>
          <li> <%= link_to "Log Out",  destroy_user_session_path, method: :delete %></li>
          <li> <%= link_to "Edit Profile", edit_user_registration_path %></li>
        <% else %>
           <li> <%= link_to "Sign Up", new_user_registration_path %></li>
          <li> <%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        

        

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_search.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class = "row">
      <h3 class = "col-md-6">Cryptos</h3>
      <div class = "form-inline col-md-6">
        <%= form_tag home_show_path, :method => 'POST' do %>
          <div class = "form-group">
            <%= text_field_tag 'sym', nil, placeholder: 'Search Crypto by Symbol', size: 50, class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= submit_tag 'Search', class: "btn btn-primary"%>
          </div>
                
        <% end %>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<%= render 'search' %>
<table class = "table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <th>Highest in 24 hr</th>
      <th>Lowest in 24 hr</th>
      <th>24 hr change %</th>
      
    </tr>
  </thead>

  <tbody>
    <% @crypto_coins.each do |coin| %>
      
        <tr>
              <td><%=   coin["name"]  %></td>
              <td><%=   coin["symbol"]  %></td>
              <td>$<%= coin["current_price"] %></td>
              <td>$<%= coin["high_24h"]%></td>
              <td>$<%= coin["low_24h"]%></td>
              <% if coin["price_change_percentage_24h"].to_d < 0 %>
                  <td style = "color:red"><%= coin["price_change_percentage_24h"]%>%</td>
              <% else %>
                  <td style = "color:green"><%= coin["price_change_percentage_24h"]%>%</td>
              <% end %>

        </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/home/show.html.erb
<%= render 'search'%>
    
<% if @currency != "No such currency" %>
    <table class = "table table-striped table-bordered table-hover">
        <thead>
            <tr>
              <th>Name</th>
              <th>Symbol</th>
              <th>Current Price</th>
              <th>Highest in 24 hr</th>
              <th>Lowest in 24 hr</th>
              <th>24 hr change %</th>
              
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><%= @currency["name"] %></td>
                <td><%= @currency["symbol"] %></td>
                <td><%= @currency["current_price"] %></td>
                <td><%= @currency["high_24h"] %></td>
                <td><%= @currency["low_24h"] %></td>
                <% if @currency["price_change_percentage_24h"].to_d < 0 %>
                  <td style = "color:red"><%= @currency["price_change_percentage_24h"]%>%</td>
                <% else %>
                  <td style = "color:green"><%= @currency["price_change_percentage_24h"]%>%</td>
                <% end %>
            </tr>
        </tbody>
    </table>

    
<% else %>
    <h1><%= @currency %></h1>
<% end %>
</div>
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Currency Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= render 'home/flash' %>
      <%= yield %>
      
    </div>
    <%= render 'home/footer' %>

  </body>
</html>